export type CurriculumIdeaOption = {
  value: string;
  label: string;
};

function toOptions(values: string[]): CurriculumIdeaOption[] {
  return values.map((value) => ({ value, label: value }));
}

export const curriculumDomainOptions = toOptions([
  "phonics",
  "reading fluency",
  "reading comprehension",
  "spelling",
  "vocabulary",
  "grammar",
  "sentence writing",
  "paragraph writing",
  "essay writing",
  "creative writing",
  "poetry",
  "literature",
  "Shakespeare",
  "mythology",
  "folklore",
  "public speaking",
  "debate",
  "logic",
  "critical thinking",
  "research skills",
  "note-taking",
  "study skills",
  "math facts",
  "number sense",
  "place value",
  "addition and subtraction",
  "multiplication",
  "division",
  "fractions",
  "decimals",
  "percentages",
  "ratios",
  "measurement",
  "money math",
  "time and calendars",
  "pre-algebra",
  "algebra",
  "geometry",
  "trigonometry",
  "calculus foundations",
  "statistics",
  "probability",
  "data literacy",
  "personal finance math",
  "biology",
  "botany",
  "zoology",
  "human anatomy",
  "physiology",
  "nutrition science",
  "health",
  "first aid",
  "chemistry",
  "kitchen chemistry",
  "physics",
  "motion and forces",
  "electricity",
  "magnetism",
  "sound and waves",
  "light and optics",
  "astronomy",
  "space exploration",
  "earth science",
  "geology",
  "minerals and rocks",
  "weather",
  "climate",
  "oceans",
  "marine science",
  "ecology",
  "conservation",
  "environmental science",
  "nature study",
  "birding",
  "insects",
  "animal behavior",
  "gardening",
  "soil science",
  "lab skills",
  "scientific method",
  "engineering design",
  "architecture",
  "bridges and structures",
  "robotics",
  "electronics",
  "computer science",
  "coding",
  "Scratch programming",
  "Python",
  "JavaScript",
  "web design",
  "game design",
  "AI literacy",
  "digital citizenship",
  "internet research",
  "typing",
  "cybersecurity basics",
  "ancient history",
  "medieval history",
  "world history",
  "U.S. history",
  "state history",
  "local history",
  "Black history",
  "Indigenous history",
  "women's history",
  "civics",
  "government",
  "law and justice",
  "economics",
  "entrepreneurship",
  "geography",
  "world geography",
  "mapmaking",
  "cartography",
  "current events",
  "comparative religion",
  "philosophy",
  "Latin",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Mandarin",
  "Japanese",
  "Korean",
  "Arabic",
  "Greek",
  "Hebrew",
  "American Sign Language",
  "music theory",
  "music history",
  "piano",
  "guitar",
  "singing",
  "choir",
  "rhythm",
  "composition",
  "drawing",
  "painting",
  "watercolor",
  "sculpture",
  "ceramics",
  "printmaking",
  "art history",
  "photography",
  "graphic design",
  "animation",
  "storyboarding",
  "filmmaking",
  "theater",
  "improv",
  "dance",
  "fashion design",
  "sewing",
  "textiles",
  "knitting",
  "woodworking",
  "home maintenance",
  "small engine repair",
  "cooking",
  "baking",
  "meal planning",
  "knife skills",
  "food preservation",
  "financial literacy",
  "budgeting",
  "investing basics",
  "career exploration",
  "college readiness",
  "test preparation",
  "SAT prep",
  "ACT prep",
  "executive function",
  "personal organization",
  "time management",
  "emotional regulation",
  "social skills",
  "leadership",
  "community service",
  "outdoor survival",
  "camping skills",
  "navigation",
  "physical fitness",
  "sports science",
  "yoga",
  "martial arts",
  "chess",
  "strategy games",
  "memory training",
  "driver readiness",
]);

export const curriculumLearnerOptions = toOptions([
  "a preschooler",
  "a kindergartener",
  "a 5-year-old",
  "a 6-year-old",
  "a 7-year-old",
  "an 8-year-old",
  "a 9-year-old",
  "a 10-year-old",
  "an elementary learner",
  "a 3rd grader",
  "a 4th grader",
  "a 5th grader",
  "a 6th grader",
  "a 7th grader",
  "an 8th grader",
  "a middle schooler",
  "a 9th grader",
  "a 10th grader",
  "a high schooler",
  "a teen who wants more independence",
  "a hesitant learner",
  "a confident beginner",
  "a complete beginner",
  "a learner with unknown prior knowledge",
  "a learner returning after a long gap",
  "a learner who needs review before moving on",
  "a learner who reads above grade level",
  "a strong reader but reluctant writer",
  "a learner with strong verbal skills",
  "a learner who freezes during math",
  "a learner who needs concrete examples",
  "a learner who prefers diagrams over text",
  "a learner who prefers stories over worksheets",
  "a learner who likes experiments",
  "a learner who prefers hands-on work",
  "a learner who wants practical real-world relevance",
  "a learner who likes building things",
  "a learner who loves projects but skips fundamentals",
  "a learner who needs short sessions",
  "a highly curious but easily distracted learner",
  "a learner who thrives on routine",
  "a learner who resists open-ended writing",
  "a learner who gets frustrated by dense instructions",
  "a perfectionist learner who avoids mistakes",
  "a learner who needs confidence-building early wins",
  "a learner who needs extra adult scaffolding",
  "a learner who can work mostly independently",
  "a learner balancing this with sports or music",
  "a learner who enjoys repetition and mastery",
  "a mixed-age household",
  "siblings working at different levels",
  "siblings who can collaborate",
  "a parent-led small group",
  "a co-op class",
  "a learner preparing for a test",
  "a learner preparing for a performance",
  "a learner who needs accommodations",
  "a learner who benefits from movement breaks",
]);

export const curriculumTimeHorizonOptions = toOptions([
  "today",
  "tomorrow",
  "over a long weekend",
  "in 3 days",
  "in 5 school days",
  "this week",
  "over 10 days",
  "in 2 weeks",
  "in 15 sessions",
  "in 20 sessions",
  "in 30 sessions",
  "in 3 weeks",
  "this month",
  "in 4 weeks",
  "in 6 weeks",
  "in 8 weeks",
  "in 12 weeks",
  "over the next 90 days",
  "as a starter module",
  "as a one-day intro",
  "as a quick reset",
  "as a review week",
  "as a catch-up plan",
  "as a bridge unit",
  "as a mini-unit",
  "as a full unit",
  "as a semester spine",
  "across one semester",
  "for the first quarter",
  "for the second quarter",
  "for a full school year",
  "for the summer",
  "for a holiday break project",
  "for a spring unit",
  "for a fall reset",
  "before a field trip",
  "after a field trip",
  "before a competition",
  "before a test date",
  "around a family trip",
  "around a busy sports season",
  "with three lessons per week",
  "with four lessons per week",
  "with one deep session per week",
]);

export const curriculumShapeOptions = toOptions([
  "a structured sequence",
  "a skill progression",
  "a topic seed",
  "a bounded material plan",
  "a timeboxed plan",
  "a project-based sequence",
  "a practical life sequence",
  "a spiral review sequence",
  "a unit-study bundle",
  "a mastery ladder",
  "a workshop cycle",
  "a survey course",
  "a lab-and-reflection sequence",
  "a studio practice sequence",
  "a discussion-centered sequence",
  "a narration-heavy sequence",
  "a portfolio-building sequence",
  "a fieldwork sequence",
  "a performance-prep sequence",
  "a capstone-first sequence",
  "an apprenticeship-style sequence",
  "an interdisciplinary thematic unit",
  "a seasonal project arc",
  "a literature-based unit",
  "a living-books sequence",
  "a Socratic discussion sequence",
  "a notebooking sequence",
  "a research-and-present sequence",
  "a build-and-test sequence",
  "a maker project sequence",
  "a game-based sequence",
  "a debate-and-defense sequence",
  "a case-study sequence",
  "a source-analysis sequence",
  "a problem-solving ladder",
  "a fundamentals-first path",
  "a confidence-first path",
  "a challenge path",
  "a remedial rebuild",
  "a gentle introduction",
  "a fast review",
  "a deep dive",
  "a cross-curricular unit",
  "a field-trip companion",
  "a family project",
  "a co-op class plan",
  "a self-paced checklist",
  "a parent-led guide",
  "a student-led inquiry",
  "a final project arc",
  "a daily practice routine",
  "a weekly rhythm",
]);

export const curriculumPacingOptions = toOptions([
  "short frequent sessions",
  "high-frequency short sessions",
  "slow and steady pacing",
  "deep work twice a week",
  "one focused session per week",
  "daily bite-sized practice",
  "a project burst",
  "weekend-heavy pacing",
  "alternating light and heavy days",
  "discussion-led pacing",
  "lab-day pacing",
  "reading-first pacing",
  "practice-first pacing",
  "review-then-extend pacing",
  "mastery-before-advance pacing",
  "spiral review cadence",
  "portfolio-checkpoint pacing",
  "performance-deadline pacing",
  "seasonal pacing",
  "immersion pacing",
  "flexible catch-up time",
  "parent-light pacing",
  "parent-guided pacing",
  "mostly independent pacing",
  "morning-only sessions",
  "afternoon project blocks",
  "four short days and one project day",
  "two lessons and one review day each week",
  "one intro day, two practice days, and one application day",
  "hands-on first, reading second",
  "read, discuss, make, reflect",
  "watch, try, explain, apply",
  "explore first, formalize later",
  "small wins before harder work",
  "warm-up, core lesson, quick win",
  "movement breaks every 15 minutes",
  "with built-in review loops",
  "with a weekly show-what-you-know moment",
  "with optional extension days",
  "with buffer days for busy weeks",
  "with a final showcase deadline",
  "with no more than 20 minutes per day",
  "with no more than 45 minutes per session",
  "with one longer weekly studio block",
]);

export const curriculumConstraintOptions = toOptions([
  "confidence-building early wins",
  "a hard time focusing",
  "limited adult prep time",
  "limited supplies",
  "limited screen time",
  "low prior knowledge",
  "mixed prior knowledge",
  "frustration with dense instructions",
  "resistance to open-ended writing",
  "resistance to memorization",
  "math anxiety",
  "reading fatigue",
  "weak fine motor stamina",
  "strong safety constraints",
  "hands-on work and visible progress",
  "real-world relevance",
  "a final project or performance",
  "a portfolio artifact",
  "a presentation at the end",
  "a field trip connection",
  "a family discussion component",
  "minimal worksheets",
  "no long lectures",
  "no expensive materials",
  "no messy supplies",
  "no daily printing",
  "mostly offline work",
  "mostly independent work",
  "parent check-ins only",
  "clear daily checkboxes",
  "short instructions",
  "movement breaks",
  "outdoor options",
  "creative choices",
  "extra challenge options",
  "built-in review",
  "memory practice",
  "retrieval practice",
  "skill gaps from last year",
  "a busy family schedule",
  "multiple siblings nearby",
  "a learner who wants choice",
  "a learner who needs routine",
  "a learner who gets overwhelmed by too many choices",
  "a learner who needs visible progress",
  "a learner who loves stories",
  "a learner who loves competition",
  "a learner who wants to make something useful",
  "a learner who needs gentle accountability",
  "clear success criteria",
  "simple assessment ideas",
  "optional enrichment paths",
  "connection to everyday life",
]);
