export type CurriculumIdeaOption = {
  value: string;
  label: string;
};

export const curriculumDomainOptions: CurriculumIdeaOption[] = [
  { value: "reading", label: "reading" },
  { value: "writing", label: "writing" },
  { value: "spelling", label: "spelling" },
  { value: "grammar", label: "grammar" },
  { value: "phonics", label: "phonics" },
  { value: "handwriting", label: "handwriting" },
  { value: "essay writing", label: "essay writing" },
  { value: "creative writing", label: "creative writing" },
  { value: "poetry", label: "poetry" },
  { value: "public speaking", label: "public speaking" },
  { value: "debate", label: "debate" },
  { value: "literature", label: "literature" },
  { value: "math facts", label: "math facts" },
  { value: "addition and subtraction", label: "addition and subtraction" },
  { value: "multiplication", label: "multiplication" },
  { value: "division", label: "division" },
  { value: "place value", label: "place value" },
  { value: "fractions", label: "fractions" },
  { value: "decimals", label: "decimals" },
  { value: "percentages", label: "percentages" },
  { value: "pre-algebra", label: "pre-algebra" },
  { value: "algebra", label: "algebra" },
  { value: "geometry", label: "geometry" },
  { value: "statistics", label: "statistics" },
  { value: "data literacy", label: "data literacy" },
  { value: "logic", label: "logic" },
  { value: "biology", label: "biology" },
  { value: "chemistry", label: "chemistry" },
  { value: "physics", label: "physics" },
  { value: "astronomy", label: "astronomy" },
  { value: "earth science", label: "earth science" },
  { value: "geology", label: "geology" },
  { value: "weather", label: "weather" },
  { value: "climate", label: "climate" },
  { value: "ecology", label: "ecology" },
  { value: "marine science", label: "marine science" },
  { value: "anatomy", label: "anatomy" },
  { value: "health", label: "health" },
  { value: "nutrition", label: "nutrition" },
  { value: "nature study", label: "nature study" },
  { value: "gardening", label: "gardening" },
  { value: "birding", label: "birding" },
  { value: "lab skills", label: "lab skills" },
  { value: "ancient history", label: "ancient history" },
  { value: "medieval history", label: "medieval history" },
  { value: "world history", label: "world history" },
  { value: "U.S. history", label: "U.S. history" },
  { value: "civics", label: "civics" },
  { value: "government", label: "government" },
  { value: "economics", label: "economics" },
  { value: "geography", label: "geography" },
  { value: "mapmaking", label: "mapmaking" },
  { value: "current events", label: "current events" },
  { value: "mythology", label: "mythology" },
  { value: "folklore", label: "folklore" },
  { value: "Spanish", label: "Spanish" },
  { value: "French", label: "French" },
  { value: "Latin", label: "Latin" },
  { value: "sign language", label: "sign language" },
  { value: "music theory", label: "music theory" },
  { value: "piano", label: "piano" },
  { value: "guitar", label: "guitar" },
  { value: "singing", label: "singing" },
  { value: "art history", label: "art history" },
  { value: "drawing", label: "drawing" },
  { value: "painting", label: "painting" },
  { value: "sculpture", label: "sculpture" },
  { value: "animation", label: "animation" },
  { value: "storyboarding", label: "storyboarding" },
  { value: "theater", label: "theater" },
  { value: "dance", label: "dance" },
  { value: "photography", label: "photography" },
  { value: "graphic design", label: "graphic design" },
  { value: "computer science", label: "computer science" },
  { value: "coding", label: "coding" },
  { value: "Scratch programming", label: "Scratch programming" },
  { value: "Python", label: "Python" },
  { value: "web design", label: "web design" },
  { value: "robotics", label: "robotics" },
  { value: "electronics", label: "electronics" },
  { value: "AI literacy", label: "AI literacy" },
  { value: "digital citizenship", label: "digital citizenship" },
  { value: "internet research", label: "internet research" },
  { value: "typing", label: "typing" },
  { value: "financial literacy", label: "financial literacy" },
  { value: "budgeting", label: "budgeting" },
  { value: "entrepreneurship", label: "entrepreneurship" },
  { value: "personal organization", label: "personal organization" },
  { value: "time management", label: "time management" },
  { value: "study skills", label: "study skills" },
  { value: "executive function", label: "executive function" },
  { value: "emotional regulation", label: "emotional regulation" },
  { value: "social skills", label: "social skills" },
  { value: "cooking", label: "cooking" },
  { value: "baking", label: "baking" },
  { value: "meal planning", label: "meal planning" },
  { value: "home maintenance", label: "home maintenance" },
  { value: "woodworking", label: "woodworking" },
  { value: "sewing", label: "sewing" },
  { value: "textiles", label: "textiles" },
  { value: "first aid", label: "first aid" },
  { value: "outdoor survival", label: "outdoor survival" },
  { value: "architecture", label: "architecture" },
  { value: "engineering design", label: "engineering design" },
  { value: "chess", label: "chess" },
  { value: "sports science", label: "sports science" },
  { value: "physical fitness", label: "physical fitness" },
  { value: "yoga", label: "yoga" },
  { value: "martial arts", label: "martial arts" },
  { value: "driver readiness", label: "driver readiness" },
  { value: "test preparation", label: "test preparation" },
  { value: "SAT prep", label: "SAT prep" },
  { value: "ACT prep", label: "ACT prep" },
  { value: "college readiness", label: "college readiness" },
  { value: "world geography", label: "world geography" },
  { value: "language arts", label: "language arts" },
  { value: "history", label: "history" },
  { value: "music", label: "music" },
  { value: "art", label: "art" },
  { value: "foreign language", label: "foreign language" },
  { value: "cooking and baking", label: "cooking and baking" },
  { value: "public speaking and debate", label: "public speaking and debate" },
];

export const curriculumLearnerOptions: CurriculumIdeaOption[] = [
  { value: "a 5-year-old", label: "a 5-year-old" },
  { value: "a 7-year-old", label: "a 7-year-old" },
  { value: "a 9-year-old", label: "a 9-year-old" },
  { value: "a 6th grader", label: "a 6th grader" },
  { value: "a 7th grader", label: "a 7th grader" },
  { value: "a hesitant learner", label: "a hesitant learner" },
  {
    value: "a strong reader but reluctant writer",
    label: "a strong reader but reluctant writer",
  },
  {
    value: "a highly curious but easily distracted learner",
    label: "a highly curious but easily distracted learner",
  },
  { value: "a learner who needs short sessions", label: "needs short sessions" },
  { value: "a learner who prefers hands-on work", label: "prefers hands-on work" },
  { value: "siblings working at different levels", label: "siblings at mixed levels" },
  { value: "a teen who wants more independence", label: "an independent teen" },
];

export const curriculumTimeHorizonOptions: CurriculumIdeaOption[] = [
  { value: "this week", label: "this week" },
  { value: "over 10 days", label: "over 10 days" },
  { value: "in 2 weeks", label: "in 2 weeks" },
  { value: "this month", label: "this month" },
  { value: "in 6 weeks", label: "in 6 weeks" },
  { value: "in 12 weeks", label: "in 12 weeks" },
  { value: "as a starter module", label: "as a starter module" },
  { value: "in 5 school days", label: "in 5 school days" },
  { value: "in 8 weeks", label: "in 8 weeks" },
  { value: "across one semester", label: "across one semester" },
  { value: "for the summer", label: "for the summer" },
  { value: "for the next 30 sessions", label: "for 30 sessions" },
];

export const curriculumShapeOptions: CurriculumIdeaOption[] = [
  { value: "a structured sequence", label: "structured sequence" },
  { value: "a skill progression", label: "skill progression" },
  { value: "a project-based sequence", label: "project sequence" },
  { value: "a practical life sequence", label: "practical life" },
  { value: "a spiral review sequence", label: "spiral review" },
  { value: "a unit-study bundle", label: "unit study" },
  { value: "a mastery ladder", label: "mastery ladder" },
  { value: "a workshop cycle", label: "workshop cycle" },
  { value: "a lab-and-reflection sequence", label: "lab and reflection" },
  { value: "a portfolio-building sequence", label: "portfolio building" },
  { value: "a seasonal project arc", label: "seasonal project" },
  { value: "an interdisciplinary thematic unit", label: "thematic unit" },
];

export const curriculumPacingOptions: CurriculumIdeaOption[] = [
  { value: "short frequent sessions", label: "short frequent sessions" },
  { value: "slow and steady pacing", label: "slow and steady" },
  { value: "deep work twice a week", label: "deep work twice weekly" },
  { value: "a project burst", label: "project burst" },
  { value: "weekend-heavy pacing", label: "weekend-heavy" },
  { value: "alternating light and heavy days", label: "light/heavy days" },
  { value: "discussion-led pacing", label: "discussion-led" },
  { value: "flexible catch-up time", label: "flexible catch-up" },
  { value: "mastery-before-advance pacing", label: "mastery first" },
];

export const curriculumConstraintOptions: CurriculumIdeaOption[] = [
  { value: "confidence-building early wins", label: "early wins" },
  { value: "a hard time focusing", label: "hard time focusing" },
  { value: "frustration with dense instructions", label: "dense instructions" },
  { value: "resistance to open-ended writing", label: "open-ended writing" },
  { value: "limited adult prep time", label: "limited adult prep" },
  { value: "strong safety constraints", label: "safety constraints" },
  { value: "low prior knowledge", label: "low prior knowledge" },
  { value: "hands-on work and visible progress", label: "hands-on progress" },
  { value: "real-world relevance", label: "real-world relevance" },
  { value: "a final project or performance", label: "final project" },
];
